# حافظه JVM مورد استفاده Gradle و Encoding ثابت UTF-8 برای متن‌های فارسی.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# فعال بودن AndroidX برای سازگاری استاندارد پروژه‌های جدید Android.
android.useAndroidX=true

# رعایت Style رسمی Kotlin در IDE و ابزارهای فرمت.
kotlin.code.style=official

# جلوگیری از تولید R کلاس حجیم برای وابستگی‌ها و سریع‌تر شدن Build.
android.nonTransitiveRClass=true
